import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const poppins = Poppins({
 variable: "--font-poppins",
 subsets: ["latin"],
 weight: "400",
});

export const metadata = {
 title: "SNHS",
 description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en" suppressHydrationWarning className={poppins.className}>
   <body className={`${poppins.variable} antialiased`}>
    <ThemeProvider
     attribute="class"
     defaultTheme="system"
     enableSystem
     disableTransitionOnChange
    >
     {children}
    </ThemeProvider>
   </body>
  </html>
 );
}
