import {
 Book,
 BookA,
 BookUser,
 Building2,
 CalendarCheck,
 File,
 Files,
 FileSpreadsheet,
 GraduationCap,
 School,
 UserRound,
 Users2,
 UsersRound,
} from "lucide-react";

export const adminNavmenu = {
 user: {
  name: "Michael Jay Angelo",
  employeeId: "123-456-7890",
  avatar: "/photo/my_profile.jpg",
 },
 navItem1: [
  {
   title: "Enrollment",
   url: "/admin/enrollment",
   icon: Files,
  },
  {
   title: "Admission",
   url: "/admin/admission",
   icon: UsersRound,
  },
  {
   title: "Registrar Management",
   url: "/admin/registrar-management",
   icon: File,
  },
 ],
 navItem2: [
  {
   title: "Curriculum",
   icon: BookUser,
   items: [
    {
     title: "Subject Listings",
     url: "/admin/registrar-management/subject-listings",
    },
   ],
  },
 ],
 navItem3: [
  {
   title: "Rooms Monitoring",
   icon: Building2,
   items: [
    {
     title: "Maintenance",
     url: "/admin/enrollment/room-maintenance",
    },
    {
     title: "View Room Schedule",
     url: "/admin/enrollment/view-room-schedule",
    },
    {
     title: "Room Listings",
     url: "/admin/enrollment/room-listings",
    },
   ],
  },
  {
   title: "Class Programs",
   icon: Book,
   items: [
    {
     title: "New Class Section",
     url: "/admin/enrollment/new-class-section",
    },
   ],
  },
  {
   title: "Faculty",
   icon: UsersRound,
   items: [
    {
     title: "Subjects Faculty Can Teach",
     url: "/admin/enrollment/subjects-faculty-can-teach",
    },
    {
     title: "Loading / Scheduling",
     url: "/admin/enrollment/loading-scheduling",
    },
   ],
  },
  {
   title: "Advising & Scheduling",
   icon: CalendarCheck,
   items: [
    {
     title: "Advise a Student",
     url: "/admin/enrollment/advise-student",
    },
   ],
  },
  {
   title: "Reports",
   icon: Files,
   items: [
    {
     title: "List of Students not Enrolled",
     url: "/admin/enrollment/student-not-enrolled-listings",
    },
    {
     title: "Enrollment Lists",
     url: "/admin/enrollment/enrollment-lists",
    },
    {
     title: "Students Schedules",
     url: "/admin/enrollment/students-schedules",
    },
   ],
  },
 ],
 navItem4: [
  // {
  //  title: "Subjects Offered",
  //  url: "/admin/admission/subjects-offered",
  //  icon: BookA,
  // },
  {
   title: "Registration",
   url: "/admin/admission/registration",
   icon: UserRound,
  },
  {
   title: "Accredited Schools List",
   url: "/admin/admission/accredited-schools-list",
   icon: School,
  },
 ],
 navItem5: [
  {
   title: "Student's Info MGMT",
   icon: UsersRound,
   items: [
    {
     title: "View/Edit Information",
     url: "/admin/admission/view-or-edit-information",
    },
    {
     title: "Upload/Delete Picture",
     url: "/admin/admission/upload-or-delete-picture",
    },
   ],
  },
 ],
};

export const teacherNavmenu = {
 user: {
  name: "Czianel F. Santos",
  employeeId: "987-654-3210",
  subjects: "Science, Filipino",
  avatar: "",
 },
 navItem1: [
  {
   title: "Class Management",
   icon: UsersRound,
   items: [
    {
     title: "Grade Sheets",
     url: "/teacher/grade-sheets",
    },
    {
     title: "Class List",
     url: "/teacher/class-list",
    },
    {
     title: "Grade Sheets Final Report",
     url: "/teacher/grade-sheets-final-report",
    },
   ],
  },
 ],
 navItem2: [
  {
   title: "Schedule",
   url: "/teacher/schedule",
   icon: CalendarCheck,
  },
 ],
 navItem3: [
  {
   title: "Documents",
   url: "/teacher/documents",
   icon: File,
  },
 ],
 navItem4: [
  {
   title: "Student's Performance",
   icon: BookUser,
   items: [
    {
     title: "Unofficial TOR",
     url: "/teacher/unofficial-tor",
    },
   ],
  },
 ],
};

export const studentNavmenu = {
 user: {
  name: "Cocjin, Jeff Eric DC.",
  studentId: "2024003",
  avatar: "",
 },
 student_personal_info: {
  student_lrn: "2024003",
  school_year: "2025-2026",
  grade_level: "10",
  class_section: "Luna",
  last_name: "Cocjin",
  first_name: "Jeff Eric",
  middle_name: "Dela Cruz",
  extension_name: "",
  date_of_birth: "2004-07-30",
  age: 21,
  gender: "Male",
  religion: "Roman Catholic",
  indeginous_people: "no",
  person_with_disability: "no",
  nationality: "Filipino",
  place_of_birth: "Premiere, Cabanatuan City, Nueva Ecija",
  phone_number: "09171234567",
  learners_residence_data: {
   contact_number_or_guradian_name: "09171234567",
   relation: "Parent",
   baranggay: "Brgy. Santor",
   municipality: "Bongabon",
   province: "Nueva Ecija",
   zip_code: "3128",
   country: "Philippines",
  },
  physical_description: {
   height: "160",
   weight: "60",
   build: "",
   eye_color: "Black",
   hair_color: "Black",
  },
  family_data: {
   fathers_last_name: "Last Name",
   fathers_first_name: "First Name",
   fathers_middle_name: "Middle Name",
   fathers_extension_name: "Extension Name",
   mothers_last_name: "Last Name",
   mothers_first_name: "First Name",
   mothers_middle_name: "Middle Name",
   mothers_extension_name: "Extension Name",
   legal_guardian_last_name: "Last Name",
   legal_guardian_first_name: "First Name",
   legal_guardian_middle_name: "Middle Name",
   legal_guardian_extension_name: "Extension Name",
  },
 },
 navItem1: [
  {
   title: "Enrollment",
   icon: File,
   items: [
    {
     title: "Subjects Enrolled",
     url: "/student/subjects-enrolled",
    },
    {
     title: "Enrolled Load Schedule",
     url: "/student/schedule",
    },
   ],
  },
  {
   title: "Academic Performance",
   icon: GraduationCap,
   items: [
    {
     title: "Grading Per SY",
     url: "/student/grading-per-sy",
    },
   ],
  },
 ],
 navItem2: [
  {
   title: "Student Clearance",
   url: "/student/student-clearance",
   icon: FileSpreadsheet,
  },
 ],
 navItem3: [
  {
   title: "Personal Information",
   icon: UserRound,
   items: [
    {
     title: "Edit Personal Info",
     url: "/student/edit-personal-information",
    },
    {
     title: "Upload Picture",
     url: "/student/upload-picture",
    },
    {
     title: "View Personal Info",
     url: "/student/view-personal-information",
    },
    {
     title: "Change Password",
     url: "/student/change-password",
    },
   ],
  },
 ],
};

export const studentList = {
 teacher: "Mr. Santos",
 subjects: ["Science", "Filipino"],
 students: [
  // Angela Guanio (Grade 7)
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024001",
   student_name: "Angela Guanio",
   quarter: "Quarter 1",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024001",
   student_name: "Angela Guanio",
   quarter: "Quarter 2",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024001",
   student_name: "Angela Guanio",
   quarter: "Quarter 3",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024001",
   student_name: "Angela Guanio",
   quarter: "Quarter 4",
   grade: "",
   remarks: "Passed",
  },

  // Carmel Loresiane Berber (Grade 7)
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024002",
   student_name: "Carmel Loresiane Berber",
   quarter: "Quarter 1",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024002",
   student_name: "Carmel Loresiane Berber",
   quarter: "Quarter 2",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024002",
   student_name: "Carmel Loresiane Berber",
   quarter: "Quarter 3",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024002",
   student_name: "Carmel Loresiane Berber",
   quarter: "Quarter 4",
   grade: "",
   remarks: "Passed",
  },

  // Jeff Eric Cocjin (Grade 7)
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024003",
   student_name: "Jeff Eric Cocjin",
   quarter: "Quarter 1",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024003",
   student_name: "Jeff Eric Cocjin",
   quarter: "Quarter 2",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024003",
   student_name: "Jeff Eric Cocjin",
   quarter: "Quarter 3",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 7",
   section: "Grade 7 - Rizal",
   subject: "Science",
   student_lrn: "2024003",
   student_name: "Jeff Eric Cocjin",
   quarter: "Quarter 4",
   grade: "",
   remarks: "Passed",
  },

  // Reiner Panelo (Grade 10)
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024101",
   student_name: "Reiner Panelo",
   quarter: "Quarter 1",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024101",
   student_name: "Reiner Panelo",
   quarter: "Quarter 2",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024101",
   student_name: "Reiner Panelo",
   quarter: "Quarter 3",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024101",
   student_name: "Reiner Panelo",
   quarter: "Quarter 4",
   grade: "",
   remarks: "Passed",
  },

  // Nico Samonte (Grade 10)
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024102",
   student_name: "Nico Samonte",
   quarter: "Quarter 1",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024102",
   student_name: "Nico Samonte",
   quarter: "Quarter 2",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024102",
   student_name: "Nico Samonte",
   quarter: "Quarter 3",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024102",
   student_name: "Nico Samonte",
   quarter: "Quarter 4",
   grade: "",
   remarks: "Passed",
  },

  // Justine Ocampo (Grade 10)
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024103",
   student_name: "Justine Ocampo",
   quarter: "Quarter 1",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024103",
   student_name: "Justine Ocampo",
   quarter: "Quarter 2",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024103",
   student_name: "Justine Ocampo",
   quarter: "Quarter 3",
   grade: "",
   remarks: "Passed",
  },
  {
   grade_level: "Grade 10",
   section: "Grade 10 - Luna",
   subject: "Filipino",
   student_lrn: "2024103",
   student_name: "Justine Ocampo",
   quarter: "Quarter 4",
   grade: "",
   remarks: "Passed",
  },
 ],
};

export const scheduleTableOne = [
 {
  time: "7:30 - 8:30 AM",
  monday: { subject: "English", adviser: "Mr. Bayudang", room: "Room 101" },
  tuesday: { subject: "Math", adviser: "Mr. Tejano", room: "Room 102" },
  wednesday: { subject: "Science", adviser: "Mr. Santos", room: "Room 103" },
  thursday: { subject: "Filipino", adviser: "Mr. Santos", room: "Room 106" },
  friday: { subject: "MAPEH", adviser: "Mr. Tejano", room: "Room 105" },
 },
 {
  time: "8:30 - 9:30 AM",
  monday: { subject: "Math", adviser: "Mr. Tejano", room: "Room 102" },
  tuesday: { subject: "Science", adviser: "Mr. Santos", room: "Room 103" },
  wednesday: { subject: "Filipino", adviser: "Mr. Santos", room: "Room 106" },
  thursday: { subject: "MAPEH", adviser: "Mr. Bayudang", room: "Room 105" },
  friday: { subject: "English", adviser: "Mr. Bayudang", room: "Room 101" },
 },
 {
  time: "9:30 - 10:00 AM",
  monday: { subject: "Recess", adviser: "", room: "" },
  tuesday: { subject: "Recess", adviser: "", room: "" },
  wednesday: { subject: "Recess", adviser: "", room: "" },
  thursday: { subject: "Recess", adviser: "", room: "" },
  friday: { subject: "Recess", adviser: "", room: "" },
 },
 {
  time: "10:00 - 11:00 AM",
  monday: { subject: "Science", adviser: "Mr. Santos", room: "Room 103" },
  tuesday: { subject: "ESP", adviser: "Mr. Seeping", room: "Room 104" },
  wednesday: { subject: "MAPEH", adviser: "Mr. Tejano", room: "Room 105" },
  thursday: { subject: "English", adviser: "Mr. Bayudang", room: "Room 101" },
  friday: { subject: "Math", adviser: "Mr. Tejano", room: "Room 102" },
 },
 {
  time: "11:00 - 12:00 NN",
  monday: { subject: "ESP", adviser: "Mr. Seeping", room: "Room 104" },
  tuesday: { subject: "MAPEH", adviser: "Mr. Bayudang", room: "Room 105" },
  wednesday: { subject: "English", adviser: "Mr. Bayudang", room: "Room 101" },
  thursday: { subject: "Math", adviser: "Mr. Tejano", room: "Room 102" },
  friday: { subject: "Filipino", adviser: "Mr. Santos", room: "Room 106" },
 },
 {
  time: "12:00 - 1:00 PM",
  monday: { subject: "Lunch", adviser: "", room: "" },
  tuesday: { subject: "Lunch", adviser: "", room: "" },
  wednesday: { subject: "Lunch", adviser: "", room: "" },
  thursday: { subject: "Lunch", adviser: "", room: "" },
  friday: { subject: "Lunch", adviser: "", room: "" },
 },
 {
  time: "1:00 - 2:00 PM",
  monday: { subject: "MAPEH", adviser: "Mr. Tejano", room: "Room 105" },
  tuesday: { subject: "English", adviser: "Mr. Bayudang", room: "Room 101" },
  wednesday: { subject: "Math", adviser: "Mr. Tejano", room: "Room 102" },
  thursday: { subject: "Science", adviser: "Mr. Santos", room: "Room 103" },
  friday: { subject: "ESP", adviser: "Mr. Seeping", room: "Room 104" },
 },
];

export const columnHeadOne = [
 "Time",
 "Monday",
 "Tuesday",
 "Wednesday",
 "Thursday",
 "Friday",
];

export const scheduleTableTwo = [
 {
  subjectCode: "ENG 10",
  subjectName: "English",
  schedule: [
   "MON 7:30 - 8:30 AM",
   "THU 10:00 - 11:00 AM",
   "WED 11:00 - 12:00 NN",
   "TUE 1:00 - 2:00 PM",
  ],
  sectionAndRoom: "Grade 10 - Luna / Room 101",
 },
 {
  subjectCode: "MATH 10",
  subjectName: "Mathematics",
  schedule: [
   "TUE 7:30 - 8:30 AM",
   "MON 8:30 - 9:30 AM",
   "FRI 10:00 - 11:00 AM",
   "THU 11:00 - 12:00 NN",
   "WED 1:00 - 2:00 PM",
  ],
  sectionAndRoom: "Grade 10 - Luna / Room 102",
 },
 {
  subjectCode: "SCI 10",
  subjectName: "Science",
  schedule: [
   "WED 7:30 - 8:30 AM",
   "MON 10:00 - 11:00 AM",
   "THU 1:00 - 2:00 PM",
  ],
  sectionAndRoom: "Grade 10 - Luna / Room 103",
 },
 {
  subjectCode: "FIL 10",
  subjectName: "Filipino",
  schedule: [
   "THU 7:30 - 8:30 AM",
   "WED 8:30 - 9:30 AM",
   "FRI 11:00 - 12:00 NN",
  ],
  sectionAndRoom: "Grade 10 - Luna / Room 106",
 },
 {
  subjectCode: "MAPEH 10",
  subjectName: "MAPEH",
  schedule: [
   "FRI 7:30 - 8:30 AM",
   "THU 8:30 - 9:30 AM",
   "WED 10:00 - 11:00 AM",
   "MON 1:00 - 2:00 PM",
  ],
  sectionAndRoom: "Grade 10 - Luna / Room 105",
 },
 {
  subjectCode: "ESP 10",
  subjectName: "ESP",
  schedule: [
   "TUE 10:00 - 11:00 AM",
   "MON 11:00 - 12:00 NN",
   "FRI 1:00 - 2:00 PM",
  ],
  sectionAndRoom: "Grade 10 - Luna / Room 104",
 },
 {
  subjectCode: "BREAK",
  subjectName: "Recess / Lunch",
  schedule: [
   "MON–FRI 9:30 - 10:00 AM (Recess)",
   "MON–FRI 12:00 - 1:00 PM (Lunch)",
  ],
  sectionAndRoom: "Grade 10 - Luna / —",
 },
];

export const columnHeadTwo = [
 "Subject Code",
 "Subject Name",
 "Schedule",
 "Section & Room No.",
];

export const studentsInfo = [
 {
  student_lrn: "2025001",
  school_year: "2025-2026",
  grade_level: "7",
  class_section: "Rizal",
  last_name: "Dela Cruz",
  first_name: "Angela",
  middle_name: "Santos",
  extension_name: "",
  date_of_birth: "2012-05-14",
  age: 13,
  gender: "Female",
  religion: "Roman Catholic",
  indeginous_people: "no",
  person_with_disability: "no",
  nationality: "Filipino",
  place_of_birth: "Cabanatuan City, Nueva Ecija",
  phone_number: "09171234567",
  learners_residence_data: {
   contact_number_or_guradian_name: "Maria Dela Cruz",
   relation: "Parent",
   baranggay: "Brgy. Santor",
   municipality: "Bongabon",
   province: "Nueva Ecija",
   zip_code: "3128",
   country: "Philippines",
  },
  physical_description: {
   height: "150",
   weight: "45",
   build: "",
   eye_color: "Brown",
   hair_color: "Black",
  },
  family_data: {
   fathers_last_name: "Dela Cruz",
   fathers_first_name: "Jose",
   fathers_middle_name: "Manalo",
   fathers_extension_name: "",
   mothers_last_name: "Reyes",
   mothers_first_name: "Maria",
   mothers_middle_name: "Villanueva",
   mothers_extension_name: "",
   legal_guardian_last_name: "Dela Cruz",
   legal_guardian_first_name: "Maria",
   legal_guardian_middle_name: "Reyes",
   legal_guardian_extension_name: "",
  },
 },
 {
  student_lrn: "2025002",
  school_year: "2025-2026",
  grade_level: "8",
  class_section: "Bonifacio",
  last_name: "Reyes",
  first_name: "Michael",
  middle_name: "Torres",
  extension_name: "",
  date_of_birth: "2011-07-22",
  age: 14,
  gender: "Male",
  religion: "Iglesia ni Cristo",
  indeginous_people: "no",
  person_with_disability: "no",
  nationality: "Filipino",
  place_of_birth: "Cabanatuan City, Nueva Ecija",
  phone_number: "09181234568",
  learners_residence_data: {
   contact_number_or_guradian_name: "Juan Reyes",
   relation: "Parent",
   baranggay: "Brgy. Santor",
   municipality: "Bongabon",
   province: "Nueva Ecija",
   zip_code: "3128",
   country: "Philippines",
  },
  physical_description: {
   height: "160",
   weight: "50",
   build: "",
   eye_color: "Black",
   hair_color: "Dark Brown",
  },
  family_data: {
   fathers_last_name: "Reyes",
   fathers_first_name: "Juan",
   fathers_middle_name: "Torres",
   fathers_extension_name: "",
   mothers_last_name: "Santos",
   mothers_first_name: "Elena",
   mothers_middle_name: "Rivera",
   mothers_extension_name: "",
   legal_guardian_last_name: "Reyes",
   legal_guardian_first_name: "Juan",
   legal_guardian_middle_name: "Torres",
   legal_guardian_extension_name: "",
  },
 },
 {
  student_lrn: "2025003",
  school_year: "2025-2026",
  grade_level: "9",
  class_section: "Luna",
  last_name: "Gomez",
  first_name: "Carmel",
  middle_name: "Villanueva",
  extension_name: "",
  date_of_birth: "2010-03-08",
  age: 15,
  gender: "Female",
  religion: "Roman Catholic",
  indeginous_people: "no",
  person_with_disability: "no",
  nationality: "Filipino",
  place_of_birth: "Cabanatuan City, Nueva Ecija",
  phone_number: "09191234569",
  learners_residence_data: {
   contact_number_or_guradian_name: "Liza Gomez",
   relation: "Parent",
   baranggay: "Brgy. Santor",
   municipality: "Bongabon",
   province: "Nueva Ecija",
   zip_code: "3128",
   country: "Philippines",
  },
  physical_description: {
   height: "155",
   weight: "47",
   build: "",
   eye_color: "Brown",
   hair_color: "Black",
  },
  family_data: {
   fathers_last_name: "Gomez",
   fathers_first_name: "Mario",
   fathers_middle_name: "Villanueva",
   fathers_extension_name: "",
   mothers_last_name: "Ramos",
   mothers_first_name: "Liza",
   mothers_middle_name: "Delos Santos",
   mothers_extension_name: "",
   legal_guardian_last_name: "Gomez",
   legal_guardian_first_name: "Liza",
   legal_guardian_middle_name: "Ramos",
   legal_guardian_extension_name: "",
  },
 },
 {
  student_lrn: "2025004",
  school_year: "2025-2026",
  grade_level: "10",
  class_section: "Mabini",
  last_name: "Garcia",
  first_name: "Carlos",
  middle_name: "Lopez",
  extension_name: "Jr.",
  date_of_birth: "2009-09-17",
  age: 16,
  gender: "Male",
  religion: "Iglesia ni Cristo",
  indeginous_people: "no",
  person_with_disability: "no",
  nationality: "Filipino",
  place_of_birth: "Cabanatuan City, Nueva Ecija",
  phone_number: "09201234570",
  learners_residence_data: {
   contact_number_or_guradian_name: "Carlos Garcia",
   relation: "Parent",
   baranggay: "Brgy. Santor",
   municipality: "Bongabon",
   province: "Nueva Ecija",
   zip_code: "3128",
   country: "Philippines",
  },
  physical_description: {
   height: "165",
   weight: "55",
   build: "",
   eye_color: "Dark Brown",
   hair_color: "Black",
  },
  family_data: {
   fathers_last_name: "Garcia",
   fathers_first_name: "Carlos",
   fathers_middle_name: "Lopez",
   fathers_extension_name: "Sr.",
   mothers_last_name: "Delos Santos",
   mothers_first_name: "Anna",
   mothers_middle_name: "Reyes",
   mothers_extension_name: "",
   legal_guardian_last_name: "Garcia",
   legal_guardian_first_name: "Carlos",
   legal_guardian_middle_name: "Lopez",
   legal_guardian_extension_name: "Sr.",
  },
 },
 {
  student_lrn: "2025005",
  school_year: "2025-2026",
  grade_level: "8",
  class_section: "Del Pilar",
  last_name: "Santos",
  first_name: "Mel",
  middle_name: "Rivera",
  extension_name: "",
  date_of_birth: "2011-11-03",
  age: 14,
  gender: "Male",
  religion: "Roman Catholic",
  indeginous_people: "no",
  person_with_disability: "no",
  nationality: "Filipino",
  place_of_birth: "Cabanatuan City, Nueva Ecija",
  phone_number: "09211234571",
  learners_residence_data: {
   contact_number_or_guradian_name: "Rosa Santos",
   relation: "Parent",
   baranggay: "Brgy. Santor",
   municipality: "Bongabon",
   province: "Nueva Ecija",
   zip_code: "3128",
   country: "Philippines",
  },
  physical_description: {
   height: "158",
   weight: "52",
   build: "",
   eye_color: "Black",
   hair_color: "Black",
  },
  family_data: {
   fathers_last_name: "Santos",
   fathers_first_name: "Ricardo",
   fathers_middle_name: "Rivera",
   fathers_extension_name: "",
   mothers_last_name: "Villanueva",
   mothers_first_name: "Rosa",
   mothers_middle_name: "Torres",
   mothers_extension_name: "",
   legal_guardian_last_name: "Santos",
   legal_guardian_first_name: "Rosa",
   legal_guardian_middle_name: "Villanueva",
   legal_guardian_extension_name: "",
  },
 },
];
